# Generated by Django 4.0.6 on 2022-07-21 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1)),
                ('total_cost', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DispEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeComponent', models.CharField(max_length=50)),
                ('trademark', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DispOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeComponent', models.CharField(max_length=50)),
                ('trademark', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InternalDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeComponent', models.CharField(max_length=50)),
                ('trademark', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('dispentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computo.dispentry')),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
            bases=('computo.dispentry',),
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('dispoutput_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computo.dispoutput')),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
            bases=('computo.dispoutput',),
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('internaldevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computo.internaldevice')),
                ('description', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('computo.internaldevice',),
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('dispentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computo.dispentry')),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
            bases=('computo.dispentry',),
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('internaldevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computo.internaldevice')),
                ('description', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('computo.internaldevice',),
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('dispoutput_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computo.dispoutput')),
                ('description', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('computo.dispoutput',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computo.computer')),
            ],
        ),
        migrations.AddField(
            model_name='computer',
            name='keyboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computo.keyboard'),
        ),
        migrations.AddField(
            model_name='computer',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computo.monitor'),
        ),
        migrations.AddField(
            model_name='computer',
            name='motherboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computo.motherboard'),
        ),
        migrations.AddField(
            model_name='computer',
            name='mouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computo.mouse'),
        ),
        migrations.AddField(
            model_name='computer',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computo.processor'),
        ),
        migrations.AddField(
            model_name='computer',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computo.speaker'),
        ),
    ]
